#!/bin/bash

ENTRY_FILE=$(TZ=":America/Los_Angeles" date -I).md

function entry_file () {
 echo $(TZ=':America/Los_Angeles' date -I).md
}

function list_entries () {
 find *.md -regextype sed \
  -regex '[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}.md' | \
  sort -n
}

case $1 in
 -e) vim "$ENTRY_FILE" ;;
 -l) list_entries "$2" ;;
 *) [ -n "@" ] && echo "$@" >> "$ENTRY_FILE" ;;
esac
